name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build, install, and package with Maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      # Step 4: Create a staging directory and copy the jar files
      - name: Create staging directory and copy jar
        run: |
          mkdir staging
          cp target/*.jar staging

      # Step 5: Upload the artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging